### ISSUE TITLE
Switch database to SQLite

### ISSUE THREAD

**Issue by PyroSamurai** [iceblade112/TrickEmu#10]
The development and resource usage of the project would benefit from using a SQLite database instead of a MySQL/MariaDB  database. SQLite databases are stand-alone and have no dependencies needed to work. This makes them far more agile and suited towards development. You can even release them with the code (though a minimal default database with update scripts  on the side is a better idea).

This project is exactly something people are running in production settings at the moment so a SQLite db should be sufficient for the project's needs.

**Comment by PyroSamurai** [comment]
I've converted the sql script to a sqlite3 database already, so I'll go ahead locally rewrite the mysql code over to sqlite3 and test it.

**Comment by PyroSamurai** [comment]
Sadly, I don't believe that use of SQLite on a cross-platform Mono project is possible at this point in time. I've tried at least 10 of the 50 or so Nuget packages for SQLite. None work well enough on both target platforms to be considered a viable solution.

System.Data.SQLite and its variants were suppose to be our best bet for cross-platform compiling since they are maintained by the SQLite project itself. Unfortunately, it is clear that they don't have enough XGL C# devs because while the project does compile, it does not run under any implementation due to incorrect location parsing of the sqlite libraries.

Because of these problems I believe this idea should be scrapped. Installing MySQL/MariaDB would be less work for devs/users than to go through the work needed to get sqlite working (the methods for which I cannot even guarantee reproducibility).

**Comment by Raymonf** [comment]
http://msgpack.org/index.html

Try this maybe?

Or... https://github.com/oysteinkrog/SQLite.Net-PCL

Or... http://www.litedb.org/

**Comment by PyroSamurai** [comment]
The SQLite.Net-PCL doesn't work, a dependency is needed that won't install.
The other two are not SQL databases. I don't really feel like dealing with that.
Unless there is problem with using MySQL/MariaDB as the database provider, it is faster to use what we are familiar with. SQLite would have been a great improvement without sacrificing much familiarity but it isn't a necessity.

**Comment by PyroSamurai** [comment]
We talked at length about this on Telegram, this idea isn't feasible. Sticking with MySQL/MariaDB.
